### ISSUE TITLE
Any help in installing or a how to guide will be appreciated. 

### ISSUE THREAD

**Issue by mehmood-baryalai** [TheoAnastasiadis/MSXTorrentPlugin#1]
Hi

Can anyone please guide me how to install this on media station x please?

I'm new to msx, and I was thinking of hosting this repo on my onedrive as a start page so can I do so?

**Comment by TheoAnastasiadis** [comment]
Hey, sorry for the late reply. I have added a readme in the in the repo, you can check it out.

Basically, my idea is to make a plugin that works much like the hmlt5 video plugin in MSX. Unfortunately in order to stream torrents directly there is a need for service worker support, and then again torrents with webSocket trackers are not that many. The webTorrent documentation is seriously lacking also. In any case, give it a try and let me know.

example .json file
```json
{"type": "pages",
    "headline": "Torrent Plugin Test",    
    "items": [{       
        "type": "separate",
        "layout": "0,0,2,4",
        "color": "msx-glass",        
        "playerLabel": "Sintel © copyright Blender Foundation | durian.blender.org",
        "action": "video:plugin:[location-of-this-plugin-in-filesystem]",
        "properties": {
            "torrent:id":"08ada5a7a6183aae1e09d831df6748d566095a10",
            "torrent:fileIdx":"6",
            "torrent:server:precedence":false,
            "button:content:icon": "settings",
            "button:content:action": "panel:request:player:options"	
        }}],
}
```
